name: iOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Archive
        env:
          REVENUECAT_API_KEY: ${{ secrets.REVENUECAT_API_KEY }}
          USERJOT_PROJECT_ID: ${{ secrets.USERJOT_PROJECT_ID }}
        run: |
          xcodebuild \
            -project Grock.xcodeproj \
            -scheme Grock \
            -configuration Release \
            -destination "generic/platform=iOS" \
            REVENUECAT_API_KEY="$REVENUECAT_API_KEY" \
            USERJOT_PROJECT_ID="$USERJOT_PROJECT_ID" \
            clean archive \
            -archivePath build/Grock.xcarchive
